export interface propertyDetails {
    propertyName : string,
    propertyAddress : string,
    price : number,
    propertyImages : string[],
    propertyType : string,
    yearBuild : number,
    lotSize : string,
    HOAFees : string,
    propertyDescription : string,
    propertyOverviewVideoURL : string,
    interestRate : number,
    propertyOwner : {
        name : string,
        designation : string,
        email : string,
        phone : string,
    },
    status : "sale" | "sold out",
    propertyAccepted : Boolean,
    views : number,
    propertyHas : {
        beds : number,
        baths : number,
        kitchen : number,
        sqrft : number,
        parking : boolean,
    },
    country : string,
    reno : number,
    arv : number,
}