export interface comparativeAddressDetails {
    address: string,
    price: number,
    status: "sale" | "sold out",
    beds: number,
    baths: number,
    size: number,
    websiteURL: string,
}

export interface propertyDetails {
    propertyName: string,
    propertyAddress: string,
    price: number,
    propertyImages: string[],
    propertyType: string,
    yearBuild: number,
    lotSize: string,
    HOAFees: string,
    propertyDescription: string,
    propertyOverviewVideoURLs: string[],
    interestRate: number,
    propertyOwner: {
        name: string,
        designation: string,
        email: string,
        phone: string,
        ownerImageURL: string,
    },
    status: "sale" | "sold out",
    propertyAccepted: Boolean,
    views: number,
    propertyHas: {
        beds: number,
        baths: number,
        kitchen: number,
        sqrft: number,
        parking: boolean,
    },
    comparativeAddress: [
        comparativeAddress1: comparativeAddressDetails,
        comparativeAddress2: comparativeAddressDetails,
        comparativeAddress3: comparativeAddressDetails,
        comparativeAddress4: comparativeAddressDetails,
    ],
    latitude: number,
    longitude: number,
    country: string,
    reno: number,
    arv: number,
}