export interface propertyDetails {
    propertyName: string,
    propertyAddress: string,
    price: number,
    propertyImages: string[],
    propertyType: string,
    yearBuild: number,
    lotSize: string,
    HOAFees: string,
    propertyDescription: string,
    propertyOverviewVideoURLs: string[],
    interestRate: number,
    propertyOwner: {
        name: string,
        designation: string,
        email: string,
        phone: string,
        ownerImageURL: string,
    },
    status: "sale" | "sold out",
    propertyAccepted: Boolean,
    views: number,
    propertyHas: {
        beds: number,
        baths: number,
        kitchen: number,
        sqrft: number,
        parking: boolean,
    },
    comparativeAddress: {
        comparativeAddress1: string,
        comparativeAddress2: string,
        comparativeAddress3: string,
        comparativeAddress4: string,
    },
    latitude: number,
    longitude: number,
    comparativeURL: string,
    websiteURL: string,
    country: string,
    reno: number,
    arv: number,
}